version: 2.1
# orbs - reusable packages for use
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
# jobs - set of instructions / functions
jobs:
  build: # job name
    docker: # env
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t carrothay/m4-node-app:$TAG .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push carrothay/m4-node-app:$TAG
      # - run:
      #     name: Build Docker image
      #     command: |
      #       echo "Building Docker image..."
      #       docker build -t m4-node-app .
      # - run:
      #     name: Log in to Docker Hub
      #     command: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      # - run:
      #     name: Push Docker image to Docker Hub
      #     command: |
      #       echo "Pushing Docker image to Docker Hub..."
      #       docker push carrothay/m4-node-app

# workflow defines what sequence will the jobs run
workflows:
  simple_workflow: # workflow name
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only:
                - main
