version: 2.1
# orbs - reusable packages for use
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
# jobs - set of instructions / functions
jobs:
  build: # job name
    docker: # env
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build and push Docker image
          command: |
            if [ "${CIRCLE_JOB}" == "test" ]; then
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker build -t my-docker-image .
              docker tag my-docker-image $DOCKER_USERNAME/my-docker-image
              docker push $DOCKER_USERNAME/my-docker-image
            else
              echo "Skipping Docker image push as test job failed."
            fi

# workflow defines what sequence will the jobs run
workflows:
  simple_workflow: # workflow name
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
